### PR TITLE
drop commit 592210895

### PR DESCRIPTION
**Pull request by Bleb1k**

### CODE REVIEW

**Comment by rando-idiot** [comment]
greg

**Comment by Bleb1k** [comment]
I fixed a typo made during merge, can you merge again

**Comment by Bleb1k** [comment]
and again

**Comment by rando-idiot** [comment]
image
one small issue: after merging, i get an error on this line

**Comment by Bleb1k** [comment]
What's the issue?

**Comment by rando-idiot** [comment]
ok what the fuck i fixed the error by removing the comma in the last line of the list

**Comment by Bleb1k** [comment]
Change round to floor, commas can't create such errors

**Comment by rando-idiot** [comment]
idfk it works

**Comment by rando-idiot** [comment]
also why change round to floor

**Comment by Bleb1k** [comment]
With length 4 for example, if random falls intoo 3.6, it will get rounded to 4 and will try `arr[4]` and that will be undefined

**Comment by rando-idiot** [comment]
ah

**Comment by rando-idiot** [comment]
but what do you think of the update

**Pull request merged**
